shellEmulator: true

trustPolicy:
  no-downgrade:
    - '!nuxt-component-meta'

packages:
  - ./
  - docs
  - playgrounds/nuxt

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@iconify-json/lucide': ^1.2.73
  '@iconify-json/simple-icons': ^1.2.58
  '@iconify-json/vscode-icons': ^1.2.33
  '@nuxt/content': ^3.10.0
  '@nuxt/devtools': ^3.1.0
  '@nuxt/eslint': ^1.11.0
  '@nuxt/image': ^2.0.0
  '@nuxt/kit': ^4.3.0
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.3.0
  '@nuxt/test-utils': ^3.20.1
  '@nuxt/ui': ^4.4.0
  '@playwright/test': ^1.57.0
  '@tanstack/vue-table': ^8.21.3
  '@types/node': latest
  '@vitest/ui': ^4.0.14
  '@vue/test-utils': ^2.4.6
  '@vueuse/nuxt': ^14.1.0
  better-sqlite3: ^12.4.1
  defu: ^6.1.4
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  happy-dom: ^20.0.11
  nuxt: ^4.3.0
  nuxt-component-meta: ^0.16.0
  nuxt-og-image: ^5.1.13
  prettier: ^3.7.4
  prettier-plugin-classnames: ^0.8.6
  scule: ^1.3.0
  shiki-stream: ^0.1.3
  shiki-transformer-color-highlight: ^1.0.0
  sortablejs: ^1.15.6
  tailwind-scrollbar: ^4.0.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vitest: ^4.0.14
  vue-tsc: ^3.1.4
  zod: ^4.1.12
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - sharp
  - unrs-resolver
  - vue-demi
peerDependencyRules:
  ignoreMissing:
    - '@tiptap/*'
