import type { TableData } from '@nuxt/ui'
import type { NuGridProps } from '../../types/props'

export const nuGridDefaults = {
  focus: {
    mode: 'cell',
    retain: false,
    cmdArrows: 'paging',
    loopNavigation: false,
    pageStep: 10,
    alignOnModel: 'nearest',
  },
  editing: {
    enabled: false,
    startKeys: 'all',
    startClicks: 'double',
    debounce: 0,
    commitOnBlur: true,
  },
  validation: {
    validateOn: 'reward',
    showErrors: 'always',
    onInvalid: 'block',
    validateOnAddRow: true,
    icon: 'i-lucide-alert-circle',
  },
  rowSelection: {
    mode: 'multi',
    placement: 'start',
    enabled: true,
    hidden: false,
  },
  actions: {
    enabled: false,
    placement: 'end',
    hidden: false,
    getActions: () => [],
    button: {
      icon: 'i-lucide-ellipsis-vertical',
      color: 'neutral',
      variant: 'ghost',
      class: 'ml-auto',
    },
  },
  layout: {
    mode: 'div',
    stickyHeaders: false,
    scrollbars: 'scroll',
    autoSize: 'fill',
    resizeMode: 'shift',
  },
  columnDefaults: {
    sortIcons: {
      unsorted: 'i-lucide-chevrons-up-down',
      asc: 'i-lucide-arrow-up',
      desc: 'i-lucide-arrow-down',
      unsortedHover: true,
      position: 'edge',
    },
    menu: {
      visibilityToggle: true,
      button: {
        icon: 'i-lucide-more-vertical',
        color: 'neutral',
        variant: 'ghost',
      },
    },
    lookup: {
      valueKey: 'value',
      labelKey: 'label',
      searchable: true,
      placeholder: 'Select...',
      clearable: false,
      autoOpen: true,
    },
    resize: false,
    reorder: false,
    wrapText: false,
  },
  virtualization: {
    enabled: false,
    estimateSize: 65,
    overscan: 20,
    dynamicRowHeights: true,
    rowHeights: {
      groupHeader: 50,
      columnHeader: 50,
      dataRow: 80,
      footer: 45,
    },
  },
  tooltip: {
    truncatedOnly: true,
    showDelay: 500,
    hideDelay: 100,
    mouseFollow: false,
  },
  multiRow: {
    enabled: false,
    rowCount: 1,
    alignColumns: false,
  },
  animation: {
    enabled: false,
    preset: 'refresh',
    duration: 300,
    easing: 'ease-out',
    stagger: 15,
    maxStagger: 120,
  },
  paging: {
    enabled: false,
    pageSize: 20,
    pageSizeSelector: [10, 20, 50, 100],
    autoPageSize: false,
    autoPageSizeMinimum: 5,
    suppressPanel: false,
  },
  cellTypes: [],
  addNewRow: false,
  rowId: 'id',
  theme: 'default',
} satisfies Partial<NuGridProps<TableData>>
